Cleanup highlight and cmp icons Format all shell scripts Enable noice again Update kitty and bat themes Better screenshots Fix term colors
Signed-off-by: Bigo <1781140+crisidev@users.noreply.github.com>

diff --git a/home/.bin/gifrecorder b/home/.bin/gifrecorder
--- a/home/.bin/gifrecorder
+++ b/home/.bin/gifrecorder
@@ -14,39 +14,47 @@ wflag=
 
 verbose="-w"
 
-while getopts :s:c:wv name
-do
+while getopts :s:c:wv name; do
 	case $name in
-	s)	s=1
+	s)
+		s=1
 		sval="$OPTARG"
-		sflag="set";;
-	c)	c=1
+		sflag="set"
+		;;
+	c)
+		c=1
 		cropDim="$OPTARG"
-		cflag="set";;
-	w)	wflag=1;;
-	v)	verbose="-V"
-		vflag="set";;
-	:)	echo "Error: please specify the number of seconds."
-		exit 2;;
-	?)	printf "Usage: [-s <seconds>] [-c x1,y1-x2,y2] [-w] [-v]\n"
-		exit 2;;
+		cflag="set"
+		;;
+	w) wflag=1 ;;
+	v)
+		verbose="-V"
+		vflag="set"
+		;;
+	:)
+		echo "Error: please specify the number of seconds."
+		exit 2
+		;;
+	?)
+		printf "Usage: [-s <seconds>] [-c x1,y1-x2,y2] [-w] [-v]\n"
+		exit 2
+		;;
 	esac
 done
 
 #screen capturing
 if [ -z "$sflag" ]; then
-    sval=5
+	sval=5
 fi
-seconds=$(echo "$sval"*5|bc)
+seconds=$(echo "$sval"*5 | bc)
 cd /tmp
 if [ -n "$vflag" ]; then
 	echo "Now recording..."
 fi
-for (( i=1; i<$seconds; i++ ))
-do
-   padi=$(printf "%04d" $i)
-   screencapture -C -t "gif" "recorderframe""$padi"".gif"
-   sleep 0.1
+for ((i = 1; i < $seconds; i++)); do
+	padi=$(printf "%04d" $i)
+	screencapture -C -t "gif" "recorderframe""$padi"".gif"
+	sleep 0.1
 done
 screencapture -C -t "gif" "recorderframe9999.gif"
 if [ -n "$vflag" ]; then
@@ -54,9 +62,15 @@ if [ -n "$vflag" ]; then
 fi
 
 #processing the frames
-framelist=$(frames=$(ls|grep -a recorderframe);echo ${frames//\n/ })
+framelist=$(
+	frames=$(ls | grep -a recorderframe)
+	echo ${frames//\n/ }
+)
 named=$(date -j +"%Y-%m-%d")
-namet=$(tim=$(date -j +"%r");echo ${tim//:/.})
+namet=$(
+	tim=$(date -j +"%r")
+	echo ${tim//:/.}
+)
 filename=$(echo "Screen shot ""$named"" at ""$namet"".gif")
 if [ -n "$cflag" ]; then
 	crop="--crop ""$cropDim"
@@ -71,7 +85,7 @@ if [ -n "$wflag" ]; then
 		crop="--crop ""$cropDim"
 	fi
 fi
-gifsicle $verbose --delay 25 --loopcount $crop $framelist > "$filename"
+gifsicle $verbose --delay 25 --loopcount $crop $framelist >"$filename"
 gifsicle $verbose -b --optimize=2 "$filename"
 mv "$filename" ~/Desktop/
 if [ -n "$vflag" ]; then
